export const CREATE_LIST_SUCCESS = 'CREATE_LIST__SUCCESS';
export const CREATE_LIST_FAILED = 'CREATE_LIST_FAILED';

export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILED = 'DELETE_LIST_FAILED';

export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAILED = 'UPDATE_LIST_FAILED';