export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILED = 'CREATE_PROJECT_FAILED';

export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';

export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILED = 'DELETE_PROJECT_FAILED';

export const ADD_VOTING_SUCCESS = 'ADD_VOTING_SUCCESS';
export const ADD_VOTING_FAILED = 'ADD_VOTING_FAILED';

export const ADD_VOTE_SUCCESS = 'ADD_VOTE_SUCCESS';
export const ADD_VOTE_FAILED = 'ADD_VOTE_FAILED';

export const DELETE_VOTING_SUCCESS = 'DELETE_VOTING_SUCCESS';
export const DELETE_VOTING_FAILED = 'DELETE_VOTING_FAILED';
